#!/bin/sh

WORKTREE=/Users/osx001/testspaces/repo/www/ 
GIT_DIR=/Users/osx001/testspaces/repo/test

cd ${GIT_DIR}
MESSAGE=$(git log -1 HEAD --pretty=format:%s) 
TIMESTAMP=`date +%s`


if [ ! -d ${WORKTREE} ]; then
	mkdir ${WORKTREE}
fi
if [[ ${MESSAGE} == *\[release\]* || ${MESSAGE} == *\[assets\]* ]];then
	echo 'releasing.....'
	git --work-tree=${WORKTREE} --git-dir=${GIT_DIR} checkout -f
	echo 'release over'
	if [[ ${MESSAGE} == *\[assets\]*  ]];then
		echo 'changing asserts code .....'
		sed -i '.bak' "s/\(\$config\['asset_flag'\] \= \)'[0-9]*';/\1'${TIMESTAMP}';/g" $WORKTREE/config.php
		echo 'change over'
	fi
	echo 'clearing cache....'
	# staff
	echo 'clear cache over'
fi
